services:
  # ----------------------------------------------------
  # Aplicación Node.js (NestJS Backend + React Frontend)
  # Build local usando backend/Dockerfile
  # ----------------------------------------------------
  node-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mi-aplicacion-nodejs
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - MQTT_BROKER_URL=mqtt://emqx
      - MQTT_USER=${MOSQUITTO_USER}
      - MQTT_PASS=${MOSQUITTO_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1h
      - DOMAIN_URL=${DOMAIN_URL}
      - NODE_ENV=production
      - PORT=8420
      - SUPER_USER_USERNAME=${SUPER_USER_USERNAME}
      - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
    ports:
      - "8420:8420"
    networks:
      - mi-red

  # ----------------------------------------------------
  # Base de Datos MongoDB
  # ----------------------------------------------------
  mongodb:
    image: mongo:7.0
    container_name: mi-database-mongo
    restart: unless-stopped
    stop_grace_period: 60s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mi-red
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ----------------------------------------------------
  # Broker EMQX (MQTT)
  # ----------------------------------------------------
  emqx:
    image: emqx/emqx:5.7.0
    container_name: mi-broker-emqx
    restart: unless-stopped
    environment:
      - "EMQX_LISTENERS__TCP__DEFAULT__BIND=1883"
      - "EMQX_AUTH__USER__1__USERNAME=${MOSQUITTO_USER}"
      - "EMQX_AUTH__USER__1__PASSWORD=${MOSQUITTO_PASS}"
      - "EMQX_NODE__COOKIE=${EMQX_NODE_COOKIE}"
    ports:
      - "1883:1883"
      - "18083:18083"
    networks:
      - mi-red

networks:
  mi-red:
