services:
  caddy:
    image: caddy:latest
    container_name: mi-caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # El volumen compartido para los certificados
      - letsencrypt-certs:/etc/letsencrypt
      # Volumen para que Certbot pueda colocar los archivos de desafío
      - caddy-webroot:/var/www/html
    environment:
      - DOMAIN_URL=${DOMAIN_URL}
    networks:
      - mi-red

  # El servicio de Certbot para obtener y renovar certificados
  certbot:
    image: certbot/certbot
    container_name: mi-certbot
    volumes:
      # Comparte los mismos volúmenes que Caddy
      - letsencrypt-certs:/etc/letsencrypt
      - caddy-webroot:/var/www/html
    # El comando se ejecutará a través del script de inicio
    command: ["--version"]

  node-app:
    image: oscarr093/monitoreotermico:1.1 # O la versión que corresponda
    container_name: mi-aplicacion-nodejs
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - MQTT_BROKER_URL=mqtt://mosquitto
      - MQTT_USER=${MOSQUITTO_USER}
      - MQTT_PASS=${MOSQUITTO_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - DOMAIN_URL=${DOMAIN_URL}
      - NODE_ENV=${NODE_ENV}
    networks:
      - mi-red

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mi-database-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - datos-mongo:/data/db
    networks:
      - mi-red

  mosquitto:
    image: eclipse-mosquitto:2.0.22-openssl
    container_name: mi-broker-mqtts
    restart: unless-stopped
    ports:
      - "8883:8883"
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      # Mosquitto ahora lee los certificados del volumen compartido
      - letsencrypt-certs:/etc/letsencrypt:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    command: sh -c "touch /mosquitto/config/password.txt && mosquitto_passwd -b /mosquitto/config/password.txt ${MOSQUITTO_USER} ${MOSQUITTO_PASS} && chmod 600 /mosquitto/config/password.txt && exec mosquitto -c /mosquitto/config/mosquitto.conf"
    networks:
      - mi-red

networks:
  mi-red:

volumes:
  datos-mongo: {}
  mosquitto-data: {}
  mosquitto-log: {}
  # Nuevos volúmenes compartidos
  letsencrypt-certs: {}
  caddy-webroot: {}
