services:
  caddy:
    image: caddy:latest
    container_name: mi-caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    environment:
      # Pasamos la variable de entorno a Caddy
      - DOMAIN_URL=${DOMAIN_URL}
    networks:
      - mi-red
    # Añadimos depends_on para que Caddy espere a que la app esté lista
    depends_on:
      - node-app

  node-app:
    image: oscarr093/monitoreotermico:1.2 # Asegúrate que el tag es el correcto
    container_name: mi-aplicacion-nodejs
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - MQTT_BROKER_URL=mqtt://mosquitto
      - MQTT_USER=${MOSQUITTO_USER}
      - MQTT_PASS=${MOSQUITTO_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - DOMAIN_URL=${DOMAIN_URL}
      - NODE_ENV=${NODE_ENV} # <-- AÑADIDO: Variable de entorno de producción
    depends_on: # <-- AÑADIDO: Asegura el orden de inicio
      - mongodb
      - mosquitto
    networks:
      - mi-red

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mi-database-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - datos-mongo:/data/db
    networks:
      - mi-red

  mosquitto:
    image: eclipse-mosquitto:2.0.22-openssl
    container_name: mi-broker-mqtts
    restart: unless-stopped
    ports:
      - "8883:8883"
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - caddy-data:/data/caddy:ro # Monta el volumen de Caddy como solo lectura
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    command: |
      set -x
      rm -f /mosquitto/config/password.txt
      echo "${MOSQUITTO_PASS}" | mosquitto_passwd -c - /mosquitto/config/password.txt ${MOSQUITTO_USER}
      cat /mosquitto/config/password.txt || echo "No se pudo crear password.txt"
      chmod 600 /mosquitto/config/password.txt
      chown root:root /mosquitto/config/password.txt
      exec mosquitto -c /mosquitto/config/mosquitto.conf
    networks:
      - mi-red

networks:
  mi-red:

volumes:
  datos-mongo: {}
  mosquitto-data: {}
  mosquitto-log: {}
  caddy-data: {}

