services:
  # ----------------------------------------------------
  # Traefik (Reverse Proxy y Gestor de SSL)
  # ----------------------------------------------------
  traefik:
    image: traefik:v3.1
    container_name: mi-traefik-proxy
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json" # Ruta DENTRO del contenedor
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # --- INICIO: SECCIÓN DE REDIRECCIÓN A HTTPS ---
      # Redirige todo el tráfico del entrypoint 'web' (HTTP) al 'websecure' (HTTPS).
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # Especifica que el esquema de la redirección debe ser 'https'.
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # --- FIN: SECCIÓN DE REDIRECCIÓN A HTTPS ---
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Bind Mount: Vincula la carpeta del host a la carpeta interna de Traefik
      - ./traefik-data:/data
    networks:
      - mi-red

  # ----------------------------------------------------
  # Extractor de Certificados (usando Bind Mounts)
  # ----------------------------------------------------
  cert-extractor:
    image: ldez/traefik-certs-dumper:latest
    container_name: mi-cert-extractor
    restart: unless-stopped
    depends_on:
      - traefik
    command: >
      file --watch
      --source /data/acme.json
      --dest /certs
      --domain-subdir
    volumes:
      # Bind Mount de solo lectura a los datos de Traefik
      - ./traefik-data:/data:ro
      # Bind Mount de escritura a la carpeta de certificados compartidos
      - ./shared-certs:/certs
    networks:
      - mi-red

  # ----------------------------------------------------
  # Aplicación Node.js (con etiquetas para Traefik)
  # ----------------------------------------------------
  node-app:
    image: oscarr093/monitoreotermico:1.0
    container_name: mi-aplicacion-nodejs
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - MQTT_BROKER_URL=mqtt://emqx
      - MQTT_USER=${MOSQUITTO_USER}
      - MQTT_PASS=${MOSQUITTO_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - DOMAIN_URL=${DOMAIN_URL}
      - NODE_ENV=production
    networks:
      - mi-red
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-app.rule=Host(`${DOMAIN_URL}`)"
      - "traefik.http.routers.node-app.entrypoints=websecure"
      - "traefik.http.routers.node-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.node-app.loadbalancer.server.port=3000"

  # ----------------------------------------------------
  # Base de Datos MongoDB (sin cambios)
  # ----------------------------------------------------
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mi-database-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - datos-mongo:/data/db # Mantenemos el volumen de Docker para la base de datos
    networks:
      - mi-red

  # ----------------------------------------------------
  # Broker EMQX (usando Bind Mounts)
  # ----------------------------------------------------
  emqx:
    image: emqx/emqx:5.7.0
    container_name: mi-broker-emqx
    restart: unless-stopped
    depends_on:
      - cert-extractor
    environment:
      - "EMQX_LISTENERS__TCP__DEFAULT__BIND=1883"
      - "EMQX_LISTENERS__SSL__DEFAULT__BIND=8883"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE=/certs/${DOMAIN_URL}/${DOMAIN_URL}.key"
      - "EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE=/certs/${DOMAIN_URL}/${DOMAIN_URL}.crt"
      - "EMQX_AUTH__USER__1__USERNAME=${MOSQUITTO_USER}"
      - "EMQX_AUTH__USER__1__PASSWORD=${MOSQUITTO_PASS}"
      - "EMQX_NODE__COOKIE=${EMQX_NODE_COOKIE}"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "18083:18083"
    volumes:
      # Bind Mount de solo lectura a la carpeta de certificados compartidos
      - ./shared-certs:/certs:ro
    networks:
      - mi-red

networks:
  mi-red:

volumes:
  datos-mongo: {} # Solo el volumen de la base de datos es gestionado por Docker

