services:
  # ----------------------------------------------------
  # Caddy (Reverse Proxy y Gestor de SSL)
  # ----------------------------------------------------
  caddy:
    image: caddy:latest
    container_name: mi-caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-certs:/etc/caddy # Volumen para compartir certificados
    environment:
      - DOMAIN_URL=${DOMAIN_URL}
    networks:
      - mi-red

  # ----------------------------------------------------
  # Aplicación Node.js (Backend)
  # ----------------------------------------------------
  node-app:
    image: oscarr093/monitoreotermico:1.0 # Apunta a tu imagen ya subida
    container_name: mi-aplicacion-nodejs
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - MQTT_BROKER_URL=mqtt://emqx
      - MQTT_USER=${MOSQUITTO_USER}
      - MQTT_PASS=${MOSQUITTO_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - DOMAIN_URL=${DOMAIN_URL}
      - NODE_ENV=production
    depends_on:
      - mongodb
      - emqx
    networks:
      - mi-red

  # ----------------------------------------------------
  # Base de Datos MongoDB
  # ----------------------------------------------------
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mi-database-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - datos-mongo:/data/db
    networks:
      - mi-red

  # ----------------------------------------------------
  # Broker EMQX (Reemplaza a Mosquitto)
  # ----------------------------------------------------
  emqx:
    image: emqx/emqx:5.7.0
    container_name: mi-broker-emqx
    restart: unless-stopped
    environment:
      - "EMQX_LISTENERS__TCP__DEFAULT__BIND=1883"
      - "EMQX_LISTENERS__SSL__DEFAULT__BIND=8883"
      - "EMQX_LISTENERS__SSL__DEFAULT__KEY_PATH=/etc/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DOMAIN_URL}/${DOMAIN_URL}.key"
      - "EMQX_LISTENERS__SSL__DEFAULT__CERT_PATH=/etc/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DOMAIN_URL}/${DOMAIN_URL}.crt"
      - "EMQX_AUTH__USER__1__USERNAME=${MOSQUITTO_USER}"
      - "EMQX_AUTH__USER__1__PASSWORD=${MOSQUITTO_PASS}"
      - "EMQX_NODE__COOKIE=$(openssl rand -hex 32)"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "18083:18083" # Puerto para el Dashboard Web de EMQX
    volumes:
      - caddy-certs:/etc/caddy:ro # Monta los certificados de Caddy en modo solo lectura
    networks:
      - mi-red

networks:
  mi-red:

volumes:
  datos-mongo: {}
  caddy-data: {}
  caddy-certs: {} # Volumen compartido para los certificados

